name: ci

on:
  # By default this will run when the activity type is "opened", "synchronize",
  # or "reopened".
  pull_request:
    branches:
      - keyswitch
  # Run when protected branches are pushed to, e.g. via merge
  push:
    branches:
      - keyswitch
  workflow_dispatch:

defaults:
  run:
    shell: bash -il -eo pipefail {0}

jobs:
  run_ci:
    runs-on: [self-hosted, fpga]

    steps:
      - name: checkout_repo
        uses: actions/checkout@v2

      - name: pre-commit
        run: pre-commit run --all-files

      - name: show_details
        run: |
          echo 'pwd'
          pwd
          echo 'whoami'
          whoami
          echo 'hostname'
          hostname

      - name: build_he-fpga
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_FPGA_DEBUG=ON -DENABLE_TESTS=ON -DENABLE_BENCHMARK=ON
          make -j

      - name: build_emulation
        run: |
          source /disk1/tools/init_env.sh
          source /disk1/tools/new_env_setup.sh
          cd build
          make emulation

      - name: build_install
        run: |
          cd build
          make install

      - name: run_tests
        run: |
          source /disk1/tools/init_env.sh
          source /disk1/tools/new_env_setup.sh
          cd build
          export FPGA_DATA_DIR="/disk1/hexl-fpga-data"
          export KEYSWITCH_DATA_DIR="${FPGA_DATA_DIR}/test-vectors"
          echo "Run tests with bitstream"
          export FPGA_BITSTREAM_DIR="${FPGA_DATA_DIR}/bitstreams"
          make tests
          echo "Run tests with emulation"
          export FPGA_BITSTREAM_DIR=
          RUN_CHOICE=1 make tests

      - name: run_bench
        run: |
          source /disk1/tools/init_env.sh
          source /disk1/tools/new_env_setup.sh
          cd build
          export FPGA_DATA_DIR="/disk1/hexl-fpga-data"
          export FPGA_BITSTREAM_DIR="${FPGA_DATA_DIR}/bitstreams"
          export KEYSWITCH_DATA_DIR="${FPGA_DATA_DIR}/test-vectors"
          make bench

      - name: build_examples
        run: |
          mkdir build-examples
          cd build-examples
          cmake ../examples/ -DCMAKE_PREFIX_PATH=$(realpath ..)/build/install/lib/cmake/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
          make -j

      - name: run_examples
        run: |
          source /disk1/tools/init_env.sh
          source /disk1/tools/new_env_setup.sh
          cd build-examples
          RUN_CHOICE=1 make examples
